name: Run All Scripts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        script: [mochaChai, vitest, jest, buntest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Bun (for buntest)
        if: matrix.script == 'buntest'
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: npm ci

      - name: Run ${{ matrix.script }}
        run: npm run ${{ matrix.script }}
